"use client";

import { useState, useEffect } from "react";
import { Header } from "@/components/header";
import { Footer } from "@/components/footer";
import { Copy, Check, Terminal, Code, Settings, ShieldCheck, ChevronRight } from "lucide-react";

// Code examples definitions
const authCode = `Authorization: Bearer sk-axon-YOUR_KEY`;

const requestFormatJSON = `{
  "action_type": "email | database | payment | chat | api_call",
  "output": "the agent output string or JSON to validate",
  "agent_id": "your_agent_identifier",
  "execution_endpoint": "https://your-system.com/execute",
  "metadata": {
    "destination": "where this output is going"
  }
}`;

const responsePassJSON = `{
  "status": "PASS",
  "confidence": 0.99,
  "message": "Validation successful"
}`;

const responseBlockJSON = `{
  "status": "BLOCK",
  "reason": "Unsafe database operation detected"
}`;

const pythonCode = `import requests

# Define validation payload
payload = {
    "action_type": "database",
    "output": "SELECT * FROM users WHERE id = 1;",
    "agent_id": "sql-agent-01",
    "execution_endpoint": "https://api.my-agent.com/execute",
    "metadata": {
        "destination": "production-db"
    }
}

# Set authorization headers
headers = {
    "Authorization": "Bearer sk-axon-YOUR_KEY",
    "Content-Type": "application/json"
}

# Send request to Axon Middleware
response = requests.post(
    "https://api.axon.dev/v1/validate",
    json=payload,
    headers=headers
)

# Handle response
result = response.json()
if result["status"] == "PASS":
    print("Safe to execute!")
else:
    print(f"Blocked: {result['reason']}")
`;

const jsCode = `const payload = {
  action_type: "database",
  output: "SELECT * FROM users WHERE id = 1;",
  agent_id: "sql-agent-01",
  execution_endpoint: "https://api.my-agent.com/execute",
  metadata: {
    destination: "production-db"
  }
};

// Send request to Axon Middleware
const response = await fetch("https://api.axon.dev/v1/validate", {
  method: "POST",
  headers: {
    "Authorization": "Bearer sk-axon-YOUR_KEY",
    "Content-Type": "application/json"
  },
  body: JSON.stringify(payload)
});

// Handle response
const result = await response.json();
if (result.status === "PASS") {
  console.log("Safe to execute!");
} else {
  console.error(\`Blocked: \${result.reason}\`);
}
`;

const n8nCode = `// 1. Add an HTTP Request Node to your workflow
// 2. Configure the Node with the following parameters:
{
  "Method": "POST",
  "URL": "https://api.axon.dev/v1/validate",
  "Headers": {
    "Authorization": "Bearer sk-axon-YOUR_KEY",
    "Content-Type": "application/json"
  },
  "Body (JSON)": {
    "action_type": "email",
    "output": "={{ $json.agent_output }}",
    "agent_id": "n8n-support-agent",
    "execution_endpoint": "https://your-n8n-webhook.com",
    "metadata": {
      "destination": "client@example.com"
    }
  }
}
// 3. Connect the output to an If Node evaluating: {{ $json.status }} === "PASS"
`;

const sections = [
  { id: "authentication", label: "Authentication" },
  { id: "request-format", label: "Request Format" },
  { id: "response-examples", label: "Response Examples" },
  { id: "action-types", label: "Action Types" },
  { id: "code-examples", label: "Code Examples" },
];

const actionTypes = [
  {
    type: "email",
    description: "Validates emails for phishing, data leaks, and grammar errors.",
    useCase: "Verify customer communications, auto-replies, and marketing emails.",
  },
  {
    type: "database",
    description: "Checks database queries for SQL injection, destructive operations, and locked tables.",
    useCase: "Inspect generated SQL statements before executing them on production databases.",
  },
  {
    type: "payment",
    description: "Validates checkout metadata, transaction amounts, and fraud compliance rules.",
    useCase: "Verify Stripe or other billing events generated by AI agents.",
  },
  {
    type: "chat",
    description: "Filters output for prompt injection, toxic language, and PII leaks.",
    useCase: "Moderate AI agent responses in real-time customer-facing chat windows.",
  },
  {
    type: "api_call",
    description: "Scans outbound requests for SSRF, API token leaks, and protocol violations.",
    useCase: "Validate webhooks, HTTP calls, and third-party integrations.",
  },
];

export default function DocsPage() {
  const [activeSection, setActiveSection] = useState("authentication");
  const [activeTab, setActiveTab] = useState<"python" | "javascript" | "n8n">("python");

  useEffect(() => {
    const handleScroll = () => {
      const scrollPosition = window.scrollY + 130; // adjust for header + spacing offset

      for (const section of sections) {
        const el = document.getElementById(section.id);
        if (el) {
          const top = el.offsetTop;
          const height = el.offsetHeight;
          if (scrollPosition >= top && scrollPosition < top + height) {
            setActiveSection(section.id);
            break;
          }
        }
      }
    };

    window.addEventListener("scroll", handleScroll);
    return () => window.removeEventListener("scroll", handleScroll);
  }, []);

  const scrollToSection = (id: string) => {
    const element = document.getElementById(id);
    if (element) {
      const headerOffset = 110; // offset to fit below Header component
      const elementPosition = element.getBoundingClientRect().top;
      const offsetPosition = elementPosition + window.pageYOffset - headerOffset;

      window.scrollTo({
        top: offsetPosition,
        behavior: "smooth",
      });
      setActiveSection(id);
    }
  };

  return (
    <div className="flex min-h-screen flex-col bg-background text-foreground">
      <Header />

      {/* Background radial glow */}
      <div className="pointer-events-none absolute inset-0 overflow-hidden">
        <div className="absolute left-1/4 top-1/4 h-[500px] w-[500px] rounded-full bg-primary/5 blur-[100px]" />
        <div className="absolute right-1/4 top-3/4 h-[600px] w-[600px] rounded-full bg-primary/5 blur-[120px]" />
      </div>

      <div className="flex-1 pt-28 pb-24 relative z-10">
        <div className="mx-auto max-w-6xl px-6">
          
          {/* Docs Header */}
          <div className="mb-12 border-b border-border/50 pb-8">
            <div className="flex items-center gap-2 text-xs font-semibold text-primary uppercase tracking-wider mb-2">
              <Terminal className="h-4 w-4" />
              Documentation
            </div>
            <h1 className="text-4xl font-bold tracking-tight text-foreground sm:text-5xl">
              Quick Start
            </h1>
            <p className="mt-3 text-lg text-muted-foreground max-w-3xl">
              Axon is a validation middleware for AI outputs. Follow this guide to authenticate your requests, structure payloads correctly, and integrate validation logic into your AI agent stack.
            </p>
          </div>

          <div className="flex flex-col lg:flex-row gap-12">
            
            {/* Sidebar Navigation */}
            <aside className="lg:w-60 shrink-0 lg:sticky lg:top-[120px] h-fit">
              <nav className="space-y-1">
                <p className="px-3 text-xs font-semibold uppercase tracking-wider text-muted-foreground/60 mb-3">
                  Overview
                </p>
                {sections.map((section) => (
                  <button
                    key={section.id}
                    onClick={() => scrollToSection(section.id)}
                    className={`flex w-full items-center justify-between rounded-lg px-3 py-2 text-left text-sm font-medium transition-all ${
                      activeSection === section.id
                        ? "bg-primary/10 text-primary border-l-2 border-primary pl-4"
                        : "text-muted-foreground hover:bg-muted/50 hover:text-foreground pl-3"
                    }`}
                  >
                    <span>{section.label}</span>
                    <ChevronRight
                      className={`h-4 w-4 opacity-0 transition-opacity ${
                        activeSection === section.id ? "opacity-100" : ""
                      }`}
                    />
                  </button>
                ))}
              </nav>
            </aside>

            {/* Documentation Content */}
            <main className="flex-1 min-w-0 space-y-16">
              
              {/* Authentication Section */}
              <section id="authentication" className="scroll-mt-64">
                <div className="flex items-center gap-3 mb-4">
                  <div className="flex h-8 w-8 items-center justify-center rounded-lg bg-primary/10 text-primary">
                    <Settings className="h-4 w-4" />
                  </div>
                  <h2 className="text-2xl font-bold text-foreground">Authentication</h2>
                </div>
                <p className="mb-6 text-muted-foreground leading-relaxed">
                  Authenticate your API requests by including your secret API key in the request headers. All requests must be sent over HTTPS. Keep your API key secure and never share it publicly.
                </p>
                <CodeBlock code={authCode} language="headers" filename="Headers" />
              </section>

              {/* Request Format Section */}
              <section id="request-format" className="scroll-mt-64">
                <div className="flex items-center gap-3 mb-4">
                  <div className="flex h-8 w-8 items-center justify-center rounded-lg bg-primary/10 text-primary">
                    <Code className="h-4 w-4" />
                  </div>
                  <h2 className="text-2xl font-bold text-foreground">Request Format</h2>
                </div>
                <p className="mb-6 text-muted-foreground leading-relaxed">
                  Axon API endpoints expect request payloads in standard JSON format. Specify the output block or command generated by your AI agent, details of the action type, and destination details.
                </p>
                <CodeBlock code={requestFormatJSON} language="json" filename="Request Payload (JSON)" />
              </section>

              {/* Response Examples Section */}
              <section id="response-examples" className="scroll-mt-64">
                <div className="flex items-center gap-3 mb-4">
                  <div className="flex h-8 w-8 items-center justify-center rounded-lg bg-primary/10 text-primary">
                    <ShieldCheck className="h-4 w-4" />
                  </div>
                  <h2 className="text-2xl font-bold text-foreground">Response Examples</h2>
                </div>
                <p className="mb-6 text-muted-foreground leading-relaxed">
                  Axon evaluates agent outputs and returns either a <code className="text-emerald-400">PASS</code> state, allowing execution, or a <code className="text-red-400">BLOCK</code> state detailing why the output was flagged as unsafe.
                </p>
                
                <div className="grid gap-6 md:grid-cols-2">
                  <div className="space-y-2">
                    <span className="inline-flex items-center rounded-full border border-emerald-500/20 bg-emerald-500/10 px-2.5 py-0.5 text-xs font-semibold text-emerald-400">
                      PASS Example
                    </span>
                    <CodeBlock code={responsePassJSON} language="json" filename="Success Response" />
                  </div>
                  <div className="space-y-2">
                    <span className="inline-flex items-center rounded-full border border-red-500/20 bg-red-500/10 px-2.5 py-0.5 text-xs font-semibold text-red-400">
                      BLOCK Example
                    </span>
                    <CodeBlock code={responseBlockJSON} language="json" filename="Blocked Response" />
                  </div>
                </div>
              </section>

              {/* Action Types Table Section */}
              <section id="action-types" className="scroll-mt-64">
                <h2 className="text-2xl font-bold text-foreground mb-4">Action Types Table</h2>
                <p className="mb-6 text-muted-foreground leading-relaxed">
                  Axon supports specific action contexts to tailor validation. Choose the appropriate action type based on the destination endpoint or the task description of the agent output.
                </p>

                <div className="overflow-hidden rounded-xl border border-border/50 bg-card/50 backdrop-blur-sm">
                  <div className="overflow-x-auto">
                    <table className="w-full border-collapse">
                      <thead>
                        <tr className="border-b border-border/50 text-left bg-muted/20">
                          <th className="px-6 py-4 text-xs font-semibold uppercase tracking-wider text-muted-foreground">
                            Action Type
                          </th>
                          <th className="px-6 py-4 text-xs font-semibold uppercase tracking-wider text-muted-foreground">
                            Description
                          </th>
                          <th className="px-6 py-4 text-xs font-semibold uppercase tracking-wider text-muted-foreground">
                            Example Use Case
                          </th>
                        </tr>
                      </thead>
                      <tbody className="divide-y divide-border/50">
                        {actionTypes.map((act) => (
                          <tr key={act.type} className="transition-colors hover:bg-muted/10">
                            <td className="px-6 py-4 whitespace-nowrap">
                              <code className="rounded-lg bg-primary/10 border border-primary/20 px-2.5 py-1 text-xs font-mono font-semibold text-primary">
                                {act.type}
                              </code>
                            </td>
                            <td className="px-6 py-4 text-sm text-foreground/90 max-w-xs md:max-w-sm">
                              {act.description}
                            </td>
                            <td className="px-6 py-4 text-sm text-muted-foreground max-w-xs">
                              {act.useCase}
                            </td>
                          </tr>
                        ))}
                      </tbody>
                    </table>
                  </div>
                </div>
              </section>

              {/* Code Examples Section */}
              <section id="code-examples" className="scroll-mt-64">
                <h2 className="text-2xl font-bold text-foreground mb-4">Code Examples</h2>
                <p className="mb-6 text-muted-foreground leading-relaxed">
                  Integrate Axon directly in your custom scripts or workflow orchestration engines. Select a language or tool to copy quick-start integration snippets.
                </p>

                {/* Tabs selection */}
                <div className="mb-4 flex border-b border-border/50">
                  {(["python", "javascript", "n8n"] as const).map((tab) => (
                    <button
                      key={tab}
                      onClick={() => setActiveTab(tab)}
                      className={`px-6 py-3 text-sm font-semibold capitalize transition-all border-b-2 ${
                        activeTab === tab
                          ? "border-primary text-primary bg-primary/5"
                          : "border-transparent text-muted-foreground hover:text-foreground"
                      }`}
                    >
                      {tab === "javascript" ? "JavaScript" : tab === "python" ? "Python" : "n8n"}
                    </button>
                  ))}
                </div>

                {/* Tab Content */}
                <div className="transition-all duration-300">
                  {activeTab === "python" && (
                    <CodeBlock code={pythonCode} language="python" filename="main.py" />
                  )}
                  {activeTab === "javascript" && (
                    <CodeBlock code={jsCode} language="javascript" filename="index.js" />
                  )}
                  {activeTab === "n8n" && (
                    <CodeBlock code={n8nCode} language="javascript" filename="n8n-node-config.json" />
                  )}
                </div>
              </section>

            </main>
          </div>

        </div>
      </div>

      <Footer />
    </div>
  );
}

// Reusable CodeBlock component
interface CodeBlockProps {
  code: string;
  language?: string;
  filename?: string;
}

function CodeBlock({ code, language, filename }: CodeBlockProps) {
  const [copied, setCopied] = useState(false);

  const handleCopy = () => {
    navigator.clipboard.writeText(code);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="overflow-hidden rounded-xl border border-border bg-card shadow-inner relative group/block">
      <div className="flex items-center justify-between border-b border-border/80 px-4 py-3 bg-muted/10">
        <div className="flex items-center gap-1.5">
          <div className="h-3 w-3 rounded-full bg-red-500/80" />
          <div className="h-3 w-3 rounded-full bg-yellow-500/80" />
          <div className="h-3 w-3 rounded-full bg-green-500/80" />
        </div>
        {filename && (
          <span className="font-mono text-xs text-muted-foreground font-medium select-none">
            {filename}
          </span>
        )}
        <button
          onClick={handleCopy}
          className="flex items-center gap-1.5 rounded-md border border-border/50 bg-secondary/50 px-2 py-1 text-xs text-muted-foreground transition-all hover:bg-muted hover:text-foreground"
        >
          {copied ? (
            <>
              <Check className="h-3.5 w-3.5 text-primary" />
              <span className="text-primary font-medium">Copied</span>
            </>
          ) : (
            <>
              <Copy className="h-3.5 w-3.5" />
              <span>Copy</span>
            </>
          )}
        </button>
      </div>
      <pre className="overflow-x-auto p-5 font-mono text-sm leading-relaxed bg-[#0c0c0c]">
        <code className="text-muted-foreground block">
          {code.split("\n").map((line, i) => (
            <span key={i} className="block min-h-[1.5rem] hover:bg-muted/5 rounded px-1 -mx-1 transition-colors">
              <span className="mr-4 inline-block w-6 select-none text-right text-muted-foreground/30 font-medium">
                {i + 1}
              </span>
              <HighlightedLine line={line} language={language} />
            </span>
          ))}
        </code>
      </pre>
    </div>
  );
}

// Light tokenizer for key languages
function HighlightedLine({ line, language }: { line: string; language?: string }) {
  if (!language) return <span>{line}</span>;

  const tokens: { text: string; className: string }[] = [];

  if (language === "json") {
    // Matches keys, strings, booleans, and numbers
    const regex = /("(?:[^"\\]|\\.)*")\s*(:)|("(?:[^"\\]|\\.)*")|(\b(?:true|false|null)\b)|(\b\d+(?:\.\d+)?\b)/g;
    let lastIndex = 0;
    let match;

    while ((match = regex.exec(line)) !== null) {
      if (match.index > lastIndex) {
        tokens.push({
          text: line.slice(lastIndex, match.index),
          className: "",
        });
      }

      if (match[1]) {
        // Key
        tokens.push({ text: match[1], className: "text-purple-400 font-semibold" });
        tokens.push({ text: match[2], className: "text-foreground" });
      } else if (match[3]) {
        // String value
        tokens.push({ text: match[3], className: "text-emerald-400" });
      } else if (match[4]) {
        // Boolean or Null
        tokens.push({ text: match[4], className: "text-orange-400" });
      } else if (match[5]) {
        // Number
        tokens.push({ text: match[5], className: "text-blue-400" });
      }
      lastIndex = regex.lastIndex;
    }

    if (lastIndex < line.length) {
      tokens.push({ text: line.slice(lastIndex), className: "" });
    }
  } else if (language === "javascript" || language === "js" || language === "typescript" || language === "ts") {
    // Matches strings, keywords, built-ins, comments
    const regex = /("(?:[^"\\]|\\.)*")|('(?:[^'\\]|\\.)*')|(\`(?:[^\`\\]|\\.)*\`)|(\b(?:const|let|var|await|async|import|from|if|else|return|function|class|new|print|console)\b)|(\b(?:fetch|JSON|stringify|log|error)\b)|(\/\/.*)/g;
    let lastIndex = 0;
    let match;

    while ((match = regex.exec(line)) !== null) {
      if (match.index > lastIndex) {
        tokens.push({
          text: line.slice(lastIndex, match.index),
          className: "",
        });
      }

      if (match[1] || match[2] || match[3]) {
        // String
        tokens.push({ text: match[0], className: "text-emerald-400" });
      } else if (match[4]) {
        // Keyword
        tokens.push({ text: match[4], className: "text-purple-400" });
      } else if (match[5]) {
        // Built-in
        tokens.push({ text: match[5], className: "text-yellow-400" });
      } else if (match[6]) {
        // Comment
        tokens.push({ text: match[6], className: "text-muted-foreground/50 italic" });
      }
      lastIndex = regex.lastIndex;
    }

    if (lastIndex < line.length) {
      tokens.push({ text: line.slice(lastIndex), className: "" });
    }
  } else if (language === "python" || language === "py") {
    // Matches strings, keywords, requests functions, comments
    const regex = /("(?:[^"\\]|\\.)*")|('(?:[^'\\]|\\.)*')|(\b(?:import|from|as|if|else|elif|return|def|class|print)\b)|(\b(?:requests|post|json)\b)|(#.*)/g;
    let lastIndex = 0;
    let match;

    while ((match = regex.exec(line)) !== null) {
      if (match.index > lastIndex) {
        tokens.push({
          text: line.slice(lastIndex, match.index),
          className: "",
        });
      }

      if (match[1] || match[2]) {
        // String
        tokens.push({ text: match[0], className: "text-emerald-400" });
      } else if (match[3]) {
        // Keyword
        tokens.push({ text: match[3], className: "text-purple-400" });
      } else if (match[4]) {
        // Built-in library/func
        tokens.push({ text: match[4], className: "text-yellow-400" });
      } else if (match[5]) {
        // Comment
        tokens.push({ text: match[5], className: "text-muted-foreground/50 italic" });
      }
      lastIndex = regex.lastIndex;
    }

    if (lastIndex < line.length) {
      tokens.push({ text: line.slice(lastIndex), className: "" });
    }
  } else if (language === "headers") {
    const regex = /^([^:]+):(.*)$/;
    const match = regex.exec(line);
    if (match) {
      return (
        <span>
          <span className="text-purple-400 font-semibold">{match[1]}:</span>
          <span className="text-emerald-400">{match[2]}</span>
        </span>
      );
    }
    return <span>{line}</span>;
  } else {
    return <span>{line}</span>;
  }

  return (
    <span>
      {tokens.map((token, i) => (
        <span key={i} className={token.className}>
          {token.text}
        </span>
      ))}
    </span>
  );
}
